[theme]
base = "dark"
primaryColor = "#D9915F"
backgroundColor = "#12100F"
secondaryBackgroundColor = "#1B1917"
textColor = "#F5F1EA"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true

[browser]
gatherUsageStats = false
